spring:
  datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://127.0.0.1:5432/springcloud
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        use_sql_comments: true
#        format_sql: true
#        show_sql: true