server:
  port: 0
spring:
  application:
    name: order-service
  config:
    import:
      - classpath:datasource.properties

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true #EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 설정, true: 갱신 된 정보만 받겠다는 설정임
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #eureka라는 엔드포인트에 우리의 마이크로서비스를 등록하겠다.

logging:
  level:DEBUG