server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/~
        git:
#          uri: file://Users/jack/99_Study/github/git-config
          uri: https://github.com/doit-jack/spring-cloud-config
#          username: []
#          password: []
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
